version: "3.9"        # optional but keeps linters happy
services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    network_mode: host
    volumes:
      - ./config/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/New_York
    restart: unless-stopped

  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:stable
    privileged: true
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/frigate:/config
      - ./frigate/media:/media/frigate
      - ./frigate/db:/opt/frigate/db
      - ./models:/models
    environment:
      - FRIGATE_MQTT_USER=hb_local
      - FRIGATE_MQTT_PASSWORD=Password1
    restart: unless-stopped

  nodered:
    container_name: nodered
    image: nodered/node-red:latest
    network_mode: host
    user: root
    volumes:
      - ./nodered/data:/data
    restart: unless-stopped

  mqtt:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.21-openssl
    network_mode: host
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/certs:/mosquitto/certs
    ports:
      - "1883:1883"
    environment:
      - TZ=America/New_York
    restart: unless-stopped

